name: hello-world-pwsh

on: 
  check_suite:
    types: [completed]

jobs:
  hello-world-pwsh:

    runs-on: windows-latest

    steps: 

       - name: check out repository code
         uses: actions/checkout@v4
       - run: |
           cd ${{ github.workspace }}
              $txt= Get-Item "hello_world.txt" 
              Write-Host $txt

  
  

  
